# what are all possible simulation settings that you want to handle?
#logging level (DEBUG, INFO, WARN, ERROR)
loglevel: DEBUG
# time per timestep (seconds)
timestep: 0.1
# number of timesteps to run
simulation_timesteps: 315300
# fraction of total length
visibility: 1.0
vehicles:
  bicycle:
    length:
      1.7
    max_speed:
      10
    max_acceleration:
      2.5
    max_angle:
      65
  car:
    length:
      14.7
    max_speed:
      50
    max_acceleration:
      3.13
    max_angle:
      40
  truck:
    length:
      50
    max_speed:
      37
    max_acceleration:
      1.0
    max_angle:
      35
  pedestrian:
    length:
      0.2
    max_speed:
      1.5
    max_acceleration:
      1.2
    max_angle:
      360

# all roads meet at an intersection centered at 0,0
roads:
  - length: 10000
    direction: 0
    speed_limit: 20
    lanes:
      - width: 5
        flow_direction: 1
        type: motor
        generator:
          # unit of time between cars (seconds)
          flow: 600
          vehicle_distribution: # must add up to 1.0
            car: 0.9
            bike: 0.0
            truck: 0.1
            motorcycle: 0.0
            pedestrian: 0.0
          attentiveness:
            # 1.0 = always attentive, 0.0 = never attentive
            average: 0.8
            width: 0.3
  - length: 100
    direction: 90
    speed_limit: 20
    lanes:
      - width: 3
        flow_direction: 1
        type: motor
        generator:
          # unit of time between cars (seconds)
          flow: 574
          vehicle_distribution: # must add up to 1.0
            car: 0.0
            bike: 0.5
            truck: 0.0
            motorcycle: 0.0
            pedestrian: 0.5
          attentiveness:
            # 1.0 = always attentive, 0.0 = never attentive
            average: 1
            width: 0.1
intersection:
  traffic_control: none
  pedestrian_crossing_mechanism: none
  bicycle_crossing_mechanism: none


